apiVersion: v1
kind: Namespace
metadata:
  name: fruittreescanner
---
apiVersion: v1
kind: Secret
metadata:
  name: fruittreescanner-secrets
  namespace: fruittreescanner
type: Opaque
stringData:
  database-url: "postgresql+asyncpg://user:password@postgres:5432/fruittreescanner"
  s3-access-key: "your-access-key"
  s3-secret-key: "your-secret-key"
